USE grocery_db;
INSERT INTO users (user_name, pass, email, address) VALUES ("Max Test", "Max Pass", "testin@email.com", "123 Fake Street");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Apples","Produce", 0.50, 30, "/images/apple.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Lettuce", "Produce", 3.25, 3, "/images/lettuce.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Carrots", "Produce", 0.35, 42, "/images/carrots.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Pears", "Produce", 0.45, 33, "/images/pear.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Radishes", "Produce", 0.28, 22, "/images/radish.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Watermelon", "Produce", 6.50, 5, "/images/watermelon.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Milk", "Dairy", 3.00, 10, "/images/milk.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Cheddar cheese", "Dairy", 4.30, 14, "/images/cheddar.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Sour cream", "Dairy", 3.25, 3, "/images/sour_cream.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Butter", "Dairy", 1.80, 23, "/images/butter.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Shredded cheese", "Dairy", 6.75, 18, "/images/shredded_cheese.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Yogurt", "Dairy", 1.39, 12, "/images/yogurt.jpeg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Whole chicken", "Meat & seafood", 12.00, 8, "/images/wholechicken.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Bacon", "Meat & seafood", 7.99, 23, "/images/bacon.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Ground beef", "Meat & seafood", 6.30, 18, "/images/ground_beef.jpeg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Flank steak", "Meat & seafood", 8.99, 5, "/images/flank_steak.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Sliced ham", "Meat & seafood", 2.49, 14, "/images/ham.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Summer sausage", "Meat & seafood", 1.89, 28, "/images/summer_sausage.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Bagels", "Bakery", 0.70, 13, "/images/bagel.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Kaiser rolls", "Bakery", 0.55, 20, "/images/kaiser.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Brownies", "Bakery", 1.25, 8, "/images/brownie.jpeg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Sourdough loaf", "Bakery", 2.25, 6, "/images/sourdough.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Baguette", "Bakery", 2.30, 13, "/images/baguette.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Chocolate chip cookies", "Bakery", 0.99, 54, "/images/cookies.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Pepperoni pizza", "Frozen", 8.30, 16, "/images/pizza.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Shrimp", "Frozen", 7.99, 10, "/images/shrimp.jpeg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Fish fillets", "Frozen", 12.35, 12, "/images/fish.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Peas", "Frozen", 6.75, 9, "/images/peas.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Fries", "Frozen", 5.89, 14, "/images/fries.jpg");
INSERT INTO groceries (name, type, price, inventory, image) VALUES ("Ice cream", "Frozen", 6.50, 7, "/images/ice_cream.jpg");

INSERT INTO groceries (name, type, price, inventory, image) VALUES ();